# Generated by Django 3.2.11 on 2022-03-07 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('home', '0006_delete_iniciotpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoticiastPage',
        ),
    ]
