# Generated by Django 3.2.11 on 2022-03-01 07:40

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.CreateModel(
            name='VideojuegosIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduccion', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('rating', models.DecimalField(decimal_places=4, max_digits=6)),
                ('link', models.URLField()),
                ('place', models.IntegerField()),
                ('year', models.IntegerField()),
                ('imagen', models.URLField(max_length=250)),
                ('cast', models.CharField(help_text='Introduzca nombres separados por comas', max_length=250)),
                ('generos', models.ManyToManyField(to='videojuegos.Genre')),
            ],
            options={
                'verbose_name': 'Videojuego',
                'verbose_name_plural': 'Videojuegos',
            },
        ),
    ]
