# Generated by Django 3.2.11 on 2022-03-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Consola',
                'verbose_name_plural': 'Consolas',
            },
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='place',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='year',
        ),
        migrations.AddField(
            model_name='videojuego',
            name='descripcion',
            field=models.TextField(default='SOME STRING', max_length=1000, verbose_name='descripcion'),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='precio',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='rating',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='consolas',
            field=models.ManyToManyField(to='videojuegos.Consola'),
        ),
    ]
