# Generated by Django 3.2.11 on 2022-03-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegos', '0002_auto_20220301_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='precio',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='rating',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
    ]
